In [2]:
# Importing Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import classification_report


In [3]:
# Load datasets

train_df= pd.read_excel("D:\\ResoluteAI Assignment\\data\\train.xlsx")
test_df= pd.read_excel("D:\\ResoluteAI Assignment\data\\test.xlsx")

In [4]:
# Data View

train_df.head()

T1  T2  T3  T4  T5  T6  T7  T8  T9  T10  T11  T12  T13  T14  T15  T16  T17  \
0 -70 -61 -66 -53 -51 -63 -82 -57 -76  -78  -66  -66  -61  -59  -73  -75  -63   
1 -77 -74 -71 -76 -65 -63 -66 -52 -55  -75  -72  -75  -74  -61  -64  -63  -53   
2 -53 -38 -55 -66 -62 -62 -65 -70 -62  -52  -56  -53  -66  -68  -72  -60  -68   
3 -72 -62 -59 -65 -65 -65 -78 -82 -83  -59  -84  -60  -64  -83  -69  -72  -95   
4 -67 -69 -65 -63 -59 -53 -70 -72 -71  -60  -61  -57  -54  -76  -61  -66  -71   

   T18 target  
0  -77    B37  
1  -63    B61  
2  -77    A19  
3  -73    A22  
4  -80    A33

In [5]:
# Shape

train_df.shape

(36752, 19)

In [6]:
# Data Info

train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36752 entries, 0 to 36751
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   T1      36752 non-null  int64 
 1   T2      36752 non-null  int64 
 2   T3      36752 non-null  int64 
 3   T4      36752 non-null  int64 
 4   T5      36752 non-null  int64 
 5   T6      36752 non-null  int64 
 6   T7      36752 non-null  int64 
 7   T8      36752 non-null  int64 
 8   T9      36752 non-null  int64 
 9   T10     36752 non-null  int64 
 10  T11     36752 non-null  int64 
 11  T12     36752 non-null  int64 
 12  T13     36752 non-null  int64 
 13  T14     36752 non-null  int64 
 14  T15     36752 non-null  int64 
 15  T16     36752 non-null  int64 
 16  T17     36752 non-null  int64 
 17  T18     36752 non-null  int64 
 18  target  36752 non-null  object
dtypes: int64(18), object(1)
memory usage: 5.3+ MB


In [7]:
# Data Analysis

train_df.describe()

T1            T2            T3            T4            T5  \
count  36752.000000  36752.000000  36752.000000  36752.000000  36752.000000   
mean     -65.865449    -64.521931    -64.574472    -65.296474    -64.462152   
std        8.737286      8.914559      8.154517      8.142803      8.068375   
min      -95.000000    -95.000000    -95.000000    -95.000000    -95.000000   
25%      -72.000000    -70.000000    -70.000000    -70.000000    -69.000000   
50%      -66.000000    -65.000000    -64.000000    -66.000000    -65.000000   
75%      -61.000000    -59.000000    -59.000000    -61.000000    -59.000000   
max      -41.000000    -37.000000    -41.000000    -39.000000    -36.000000   

                 T6            T7            T8            T9           T10  \
count  36752.000000  36752.000000  36752.000000  36752.000000  36752.000000   
mean     -63.318731    -67.030202    -66.591260    -65.692479    -65.555181   
std        8.651501      9.257529     10.160193     10.598247     10.408147   
min      -95.000000    -95.000000    -95.000000    -95.000000    -95.000000   
25%      -69.000000    -74.000000    -75.000000    -73.000000    -73.000000   
50%      -63.000000    -66.000000    -66.000000    -65.000000    -65.000000   
75%      -57.000000    -60.000000    -59.000000    -58.000000    -58.000000   
max      -39.000000    -45.000000    -39.000000    -39.000000    -37.000000   

                T11           T12           T13           T14           T15  \
count  36752.000000  36752.000000  36752.000000  36752.000000  36752.000000   
mean     -65.681922    -66.244204    -63.962614    -64.399080    -64.550011   
std        9.453958      8.866239      8.254217      9.562839      9.207343   
min      -95.000000    -95.000000    -95.000000    -95.000000    -95.000000   
25%      -71.000000    -72.000000    -69.000000    -70.000000    -70.000000   
50%      -65.000000    -66.000000    -63.000000    -64.000000    -65.000000   
75%      -59.000000    -61.000000    -58.000000    -58.000000    -58.000000   
max      -40.000000    -43.000000    -43.000000    -39.000000    -38.000000   

                T16           T17           T18  
count  36752.000000  36752.000000  36752.000000  
mean     -64.136782    -65.910726    -66.590417  
std       10.540542     10.071973     10.600992  
min      -95.000000    -95.000000    -95.000000  
25%      -71.000000    -72.000000    -74.000000  
50%      -63.000000    -65.000000    -66.000000  
75%      -57.000000    -59.000000    -59.000000  
max      -40.000000    -43.000000    -39.000000

In [8]:
# Check Null Values

train_df.isnull().sum()

T1        0
T2        0
T3        0
T4        0
T5        0
T6        0
T7        0
T8        0
T9        0
T10       0
T11       0
T12       0
T13       0
T14       0
T15       0
T16       0
T17       0
T18       0
target    0
dtype: int64

In [9]:
# Check Duplicates

train_df.duplicated().sum()

1267

In [10]:
train_df.loc[train_df.duplicated()]

T1  T2  T3  T4  T5  T6  T7  T8  T9  T10  T11  T12  T13  T14  T15  T16  \
870   -61 -60 -56 -55 -49 -62 -72 -63 -66  -68  -64  -61  -57  -59  -64  -65   
889   -64 -70 -63 -68 -61 -57 -61 -56 -66  -70  -68  -65  -73  -65  -49  -45   
995   -67 -66 -63 -59 -61 -43 -64 -65 -82  -61  -59  -75  -57  -52  -53  -55   
1084  -67 -65 -63 -60 -62 -48 -64 -65 -80  -61  -58  -75  -57  -52  -53  -55   
1887  -65 -67 -65 -65 -60 -56 -78 -76 -78  -64  -62  -70  -57  -70  -59  -64   
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
36673 -64 -57 -70 -64 -77 -69 -79 -80 -78  -55  -47  -62  -62  -80  -69  -67   
36704 -63 -71 -65 -71 -77 -68 -95 -80 -75  -63  -68  -70  -81  -95  -75  -95   
36707 -64 -72 -63 -68 -61 -57 -62 -54 -65  -70  -67  -65  -72  -65  -49  -44   
36714 -64 -67 -63 -68 -69 -64 -60 -79 -67  -75  -71  -63  -58  -51  -50  -55   
36746 -60 -61 -53 -54 -68 -60 -78 -69 -73  -69  -66  -56  -49  -67  -62  -72   

       T17  T18 target  
870    -66  -68    B29  
889    -52  -50    A72  
995    -59  -65    A48  
1084   -59  -64    A48  
1887   -79  -69    A34  
...    ...  ...    ...  
36673  -79  -79    A18  
36704  -82  -95     B5  
36707  -50  -50    A72  
36714  -61  -57    A49  
36746  -79  -68    A30  

[1267 rows x 19 columns]

Duplicates can affect the results of clustering algorithms because they artificially inflate the importance of certain data points. If the duplicates are not removed, the clustering algorithm may assign undue weight to those points, potentially biasing the results.

In [11]:
train_df=train_df.drop_duplicates()

In [12]:
train_df.duplicated().sum()

0

In [13]:
x_train= train_df.iloc[:, :-1]
y_train= train_df.iloc[:,-1]

In [14]:
y_train.unique()

array(['B37', 'B61', 'A19', 'A22', 'A33', 'A75', 'A41', 'B14', 'B80',
       'B64', 'A1', 'B21', 'A70', 'B57', 'B9', 'B50', 'B31', 'A21', 'B30',
       'A4', 'B40', 'B6', 'A64', 'A25', 'B18', 'A66', 'A53', 'B73', 'A50',
       'B25', 'A29', 'A35', 'A3', 'A46', 'B45', 'A36', 'B5', 'A79', 'A32',
       'B23', 'A7', 'A62', 'A71', 'A58', 'A9', 'B63', 'B51', 'B8', 'B36',
       'A14', 'A15', 'A24', 'B38', 'A10', 'B4', 'A37', 'A12', 'B41',
       'A17', 'B49', 'B71', 'B59', 'B39', 'B29', 'A76', 'B58', 'B28',
       'A77', 'A67', 'B24', 'A31', 'A34', 'A5', 'B34', 'A11', 'B16',
       'B20', 'A63', 'B53', 'A73', 'A44', 'A69', 'A56', 'A54', 'A55',
       'B11', 'A42', 'B22', 'B67', 'A74', 'A57', 'A8', 'B46', 'B15',
       'A51', 'A40', 'A59', 'A72', 'B32', 'A2', 'A13', 'B17', 'A65',
       'A52', 'A47', 'B47', 'B77', 'B3', 'B35', 'B44', 'A80', 'B43',
       'B54', 'B75', 'A49', 'B52', 'B33', 'B2', 'B1', 'A39', 'B7', 'A20',
       'A18', 'B12', 'A27', 'A6', 'A68', 'B72', 'B66', 'B69', 'A26',
   

###### Most classifiers in scikit-learn expect the target variable to be numeric, not categorical

##### Label encoding is typically used for encoding categorical target variables (y_train) when performing classification tasks, especially when there are more than two classes. One-hot encoding is not usually applied to target variables because it can introduce multicollinearity issues and may not be suitable for classification tasks.

In [15]:
label_encoder = LabelEncoder()

In [16]:
y_train_encoded = label_encoder.fit_transform(y_train)

# Train-test-split

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train_encoded, test_size=0.2, random_state=42)


# Model Training

In [18]:
numeric_features = x_train.columns

In [19]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features)],
         remainder='passthrough'
)

In [20]:
models = {
    'Random Forest': Pipeline([
        ('preprocessor', preprocessor),
        ('classifier', RandomForestClassifier())
    ]),
    'SVC': Pipeline([
        ('preprocessor', preprocessor),
        ('classifier', SVC())
    ]),
    'XGBoost Classifier': Pipeline([
        ('preprocessor', preprocessor),
        ('classifier', XGBClassifier())
    ])
}

In [21]:
trained_models = {}
for model_name, model in models.items():
    print(f"Training {model_name}...")
    model.fit(x_train, y_train)
    trained_models[model_name] = model
    # Generate classification report
    y_pred_train = model.predict(x_train)
    print(f"Classification Report for {model_name}:\n", classification_report(y_train, y_pred_train))

Training Random Forest...


Classification Report for Random Forest:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       157
           1       1.00      1.00      1.00       171
           2       1.00      1.00      1.00       173
           3       1.00      1.00      1.00       167
           4       1.00      1.00      1.00       167
           5       1.00      1.00      1.00       321
           6       1.00      1.00      1.00       325
           7       1.00      1.00      1.00       160
           8       1.00      1.00      1.00       160
           9       1.00      1.00      1.00        86
          10       1.00      1.00      1.00       159
          11       1.00      1.00      1.00       104
          12       1.00      1.00      1.00       173
          13       1.00      1.00      1.00       298
          14       1.00      1.00      1.00       177
          15       1.00      1.00      1.00       163
          16       1.00      1.00      

In [22]:
test_predictions = {}
for model_name, model in trained_models.items():
    predictions = model.predict(test_df)
    test_predictions[model_name] = predictions

In [23]:
for model_name, predictions in test_predictions.items():
    print(f"Predictions for {model_name}:")
    print(predictions)

Predictions for Random Forest:
[151   1 141 ... 145  31  78]
Predictions for SVC:
[151   1 141 ... 145  31  78]
Predictions for XGBoost Classifier:
[151   1 141 ... 145  31  78]


In [24]:
task2_output = {
    'Random Forest Predictions': test_predictions['Random Forest'],
    'SVC Predictions': test_predictions['SVC'],
    'XGBoost Classifier Predictions': test_predictions['XGBoost Classifier']
}

In [25]:
df_task2 = pd.DataFrame(task2_output)

In [26]:
df_task2.to_csv('task2_output.csv', index=False)